### ISSUE TITLE
X axis readout

### ISSUE THREAD

**Issue by jcul3351** [strykeforce/grapher#9]
The plus and minus buttons on the X axis are PERFECT!  What would be a nice add is a digital readout that tells you how many seconds are displayed on the entire X axis.  When I zoom in and out I normally know where I want to get to but have to spend time looking at the scrolling numbers to figure it out.  A display would eliminate that challenge.

**Comment by rabsamu** [comment]
There is now a display that shows how many seconds are currently visible.
